server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/whisp_auth
    username: seu_usuario
    password: sua_senha

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: seu_secret_base64_aqui
  expiration: 900000
  refresh-expiration: 604800000