server:
  port: 8082

spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/whisp_chat
    username: seu_usuario
    password: sua_senha

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: seu_secret_base64_aqui
  expiration: 900000